services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    networks:
      - cassandra_network
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=user@123
      - MINIO_DEFAULT_BUCKETS=test-bucket



  # nestjs:
  #   build:
  #     context: .  # Ensure this is the root directory where your Dockerfile is located
  #     dockerfile: Dockerfile
  #   container_name: nestjs_app
  #   ports:
  #     - "3100:3100"
  #   depends_on:
  #     - cassandra
  #   environment:
  #     CASSANDRA_HOST: cassandra
  #     CASSANDRA_PORT: 9042
  #   networks:
  #     - cassandra_network

networks:
  cassandra_network:
    driver: bridge
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local
